---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-ca
  namespace: monitoring
  labels:
    app: kcert-demo
type: Opaque
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWekNCL3FBREFnRUNBZ2dZMVl1MTBWN0NzREFLQmdncWhrak9QUVFEQWpBWU1SWXdGQVlEVlFRREV3MXQKYjI1cGRHOXlhVzVuTFdOaE1CNFhEVEkyTURreE5URTFNek0xT1ZvWERUTXhNRGt4TkRFMk16TTFPVm93R0RFVwpNQlFHQTFVRUF4TU5iVzl1YVhSdmNtbHVaeTFqWVRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBCkJDamlCV21MUjU4UnRKdTJEd3diTFJzMWJVdGRPOW1uUzBLRmRSTnFPcHdxMk9QSU5ZY0tzSHhGRmtNNG9yRFkKcW9KUFB5eHI2c2NyazMxQlczWEg5MHFqTWpBd01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRQpGQkNQUHZHdktLNzRIWlhaNi9Cd2lUR0UrbkQ5TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUcreUV4TUJ1WWczCmFqU1RoL0czS1lKemNlQ2NkYWc4NXF1b2o0U3FwaDB4QWlFQTVUNGNlRnZmcW13QWEwOHJGZ0p0dm43ajZwZ3gKamthT3hKK08wRVdYd3pNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-api-tls
  namespace: monitoring
  labels:
    app: kcert-demo
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJUakNCOUtBREFnRUNBZ2dZMVl1MTBXaGppREFLQmdncWhrak9QUVFEQWpBWU1SWXdGQVlEVlFRREV3MXQKYjI1cGRHOXlhVzVuTFdOaE1CNFhEVEkyTURreE5URTFNek0xT1ZvWERUSTNNVEF5TURFMk16TTFPVm93SFRFYgpNQmtHQTFVRUF4TVNZWEJwTG0xdmJtbDBiM0pwYm1jdWMzWmpNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFVlRvQ2hocU9Va3g0blIyRERoYWJjYnVTRmRpOGFuemVjdkVqMHNXU3Y3MENKbGZBT2x4L3F5cnQKSnp2N0JuWGZ2aEtpMjcrMmhuOXV5NTU0VkpNNXc2TWpNQ0V3SHdZRFZSMGpCQmd3Rm9BVUVJOCs4YThvcnZnZApsZG5yOEhDSk1ZVDZjUDB3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQVBKZlEzbDQzM2ZGU1ZYQm1zcjI0WEdSCmJxUEFSTUFwUU1HaE5JM1BJS1NPQWlFQXQyVVkvTmlKcEh1RUU3Y29BSW94MCtnMWU0WU1nKzh0S2lKTVVsd3QKU1hZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-grafana-tls
  namespace: monitoring
  labels:
    app: kcert-demo
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJVRENCK0tBREFnRUNBZ2dZMVl1MTBXemYrREFLQmdncWhrak9QUVFEQWpBWU1SWXdGQVlEVlFRREV3MXQKYjI1cGRHOXlhVzVuTFdOaE1CNFhEVEkyTURreE5URTFNek0xT1ZvWERUSTJNVEF3TlRFMk16TTFPVm93SVRFZgpNQjBHQTFVRUF4TVdaM0poWm1GdVlTNXRiMjVwZEc5eWFXNW5Mbk4yWXpCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJPN1NwOGFCVU1RRHloOHdTOTFGZWVMQmR4YWtoM3p2UkJEQTRFZWRXYXRadlRjMHhvZVoKTjFPS2poSkowYzZHRXhJZC9wWmt0a3dxM3dnQVduTnEya3FqSXpBaE1COEdBMVVkSXdRWU1CYUFGQkNQUHZHdgpLSzc0SFpYWjYvQndpVEdFK25EOU1Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lEYVdJRjkzWUtpa2RoVDBiQVJjCkcwY29SVXN3eWlFK3cxOWEvbVVVcE9WT0FpQTVBV3RpbW50ODcyOXdnbklwYjl5T0hhVTQ0YjlnUEE4b0NKVi8KRllpbEZ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-alertmanager-tls
  namespace: monitoring
  labels:
    app: kcert-demo
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL2FBREFnRUNBZ2dZMVl1MTBYRllnREFLQmdncWhrak9QUVFEQWpBWU1SWXdGQVlEVlFRREV3MXQKYjI1cGRHOXlhVzVuTFdOaE1CNFhEVEkyTURreE5URTFNek0xT1ZvWERUSTJNRGt5TURFMk16TTFPVm93SmpFawpNQ0lHQTFVRUF4TWJZV3hsY25SdFlXNWhaMlZ5TG0xdmJtbDBiM0pwYm1jdWMzWmpNRmt3RXdZSEtvWkl6ajBDCkFRWUlLb1pJemowREFRY0RRZ0FFbXl0YzQyYWM2dDVYYlJ0SVUwZlVoRHNMMUYzdFVYVnZ1RThaeXpIaDdVSlMKTUpYYjFMUTJUTy9KWktkMVFCejFKd01oKys2SmVDRXNNeTVDVXdhaTJxTWpNQ0V3SHdZRFZSMGpCQmd3Rm9BVQpFSTgrOGE4b3J2Z2RsZG5yOEhDSk1ZVDZjUDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU50ejMvRThHcXVhCk9mUldjaVlsb0hzdnlldHJEZjRuRzB3cHdqYm1LbXk2QWlBRm9Zd1pPZEVYMkxQTDdLL1dQdDJiVlkyK3hjWDUKcDNXanBxZXQyZTZCd2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
