#!/usr/bin/env bash
# gen-test-certs.sh — regenerate tests/integration/fixtures/01-secrets.yaml
#
# WHY THIS SCRIPT EXISTS
# ----------------------
# macOS ships LibreSSL (not OpenSSL). LibreSSL's `openssl req -newkey ec`
# encodes EC public keys with **explicit curve parameters** instead of a named
# OID. Go's crypto/x509 only accepts the named-OID form; it silently returns
# "x509: invalid ECDSA parameters" and the scanner skips the cert entirely.
#
# The fix is the two-step approach:
#   openssl ecparam -name prime256v1 -genkey -noout   # forces named-curve key
#   openssl req -new -x509 -key ...                   # signs with that key
#
# Alpine Linux's musl-based OpenSSL (used inside the fixture pod init container
# in 02-pod.yaml) emits named OIDs by default, so pod certs need no workaround.
# Only the pre-baked Secrets in 01-secrets.yaml need this script.
#
# EXPIRY WINDOWS (relative to today at run time)
#   expired  — fixed pre-baked cert, NotAfter already in the past
#   critical — 4 days  (inside the 7-day critical threshold)
#   warning  — 20 days (inside the 30-day warning threshold)
#   healthy  — 365 days (well outside all thresholds)
#
# Usage:
#   make gen-test-certs          (preferred)
#   ./scripts/gen-test-certs.sh  (direct)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/tests/integration/fixtures/01-secrets.yaml"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# ── expired cert ──────────────────────────────────────────────────────────────
# Extract the pre-baked P-256 named-curve cert from the pod ConfigMap in 02-pod.yaml.
# Its NotAfter=2026-09-13 is fixed in the past. Never regenerate it.
#
# Source of truth is the PEM embedded in 02-pod.yaml under `server.crt: |`.
# We extract it at runtime so there's a single authoritative copy.
POD_YAML="$REPO_ROOT/tests/integration/fixtures/02-pod.yaml"
EXPIRED_PEM="$(awk '/BEGIN CERTIFICATE/,/END CERTIFICATE/' "$POD_YAML" | sed 's/^    //')"
EXPIRED_B64="$(printf '%s\n' "$EXPIRED_PEM" | base64 | tr -d '\n')"

# ── helpers ───────────────────────────────────────────────────────────────────

gen_cert() {
  local name="$1" cn="$2" days="$3"
  # Two-step: ecparam forces prime256v1 named-curve key;
  # req -new -x509 signs it — avoids LibreSSL explicit-params encoding.
  openssl ecparam -name prime256v1 -genkey -noout -out "$TMPDIR/${name}.key" 2>/dev/null
  openssl req -new -x509 \
    -key "$TMPDIR/${name}.key" \
    -out "$TMPDIR/${name}.crt" \
    -subj "/CN=${cn}" \
    -days "$days" 2>/dev/null
}

verify_go() {
  local certpath="$1" label="$2"
  # Write a tiny Go program to a temp file and run it
  local prog="$TMPDIR/verify_cert.go"
  cat > "$prog" <<'GOEOF'
package main

import (
  "crypto/x509"
  "encoding/pem"
  "fmt"
  "os"
)

func main() {
  data, _ := os.ReadFile(os.Args[1])
  block, _ := pem.Decode(data)
  if block == nil {
    fmt.Fprintf(os.Stderr, "FAIL %s: pem.Decode returned nil\n", os.Args[2])
    os.Exit(1)
  }
  cert, err := x509.ParseCertificate(block.Bytes)
  if err != nil {
    fmt.Fprintf(os.Stderr, "FAIL %s: %v\n", os.Args[2], err)
    os.Exit(1)
  }
  fmt.Printf("  OK  %-10s  CN=%-30s  NotAfter=%s\n",
    os.Args[2], cert.Subject.CommonName, cert.NotAfter.Format("2006-01-02"))
}
GOEOF
  go run "$prog" "$certpath" "$label"
}

b64() { base64 < "$1" | tr -d '\n'; }

# ── generate ──────────────────────────────────────────────────────────────────

echo "==> Generating integration test certs (P-256 named curve)..."
gen_cert critical "critical.example.com" 4
gen_cert warning  "warning.example.com"  20
gen_cert healthy  "healthy.example.com"  365

echo "==> Verifying with Go crypto/x509..."
verify_go "$TMPDIR/critical.crt" critical
verify_go "$TMPDIR/warning.crt"  warning
verify_go "$TMPDIR/healthy.crt"  healthy
echo "  SKIP expired  (pre-baked named-curve cert, NotAfter 2026-09-13)"

CRITICAL_B64=$(b64 "$TMPDIR/critical.crt")
WARNING_B64=$(b64  "$TMPDIR/warning.crt")
HEALTHY_B64=$(b64  "$TMPDIR/healthy.crt")

# ── write ─────────────────────────────────────────────────────────────────────

cat > "$OUT" <<YAML
# AUTO-GENERATED by scripts/gen-test-certs.sh — do not edit by hand.
#
# Certs use P-256 named-curve keys (two-step ecparam + req) so Go's
# crypto/x509 can parse them. macOS LibreSSL one-step -newkey ec emits
# explicit curve parameters which Go rejects with "invalid ECDSA parameters".
#
# Regenerate: make gen-test-certs
apiVersion: v1
kind: Secret
metadata:
  name: expired-secret
  namespace: kcert-integration
type: Opaque
data:
  tls.crt: ${EXPIRED_B64}
---
apiVersion: v1
kind: Secret
metadata:
  name: critical-secret
  namespace: kcert-integration
type: Opaque
data:
  tls.crt: ${CRITICAL_B64}
---
apiVersion: v1
kind: Secret
metadata:
  name: warning-secret
  namespace: kcert-integration
type: Opaque
data:
  tls.crt: ${WARNING_B64}
---
apiVersion: v1
kind: Secret
metadata:
  name: healthy-secret
  namespace: kcert-integration
type: Opaque
data:
  tls.crt: ${HEALTHY_B64}
YAML

echo ""
echo "==> Written: $OUT"
echo ""
echo "Apply to cluster:"
echo "  kubectl apply -f tests/integration/fixtures/"
